### ISSUE TITLE
Volcania

### ISSUE THREAD

**Issue by KingDeadKnight** [antokiller/test#2]
Hello, why is Volcania closed? What's wrong with it? Can i help? I love that server men

**Comment by sowahq** [comment]
He was destined to close.

**Comment by MrReskill** [comment]
أمي لديها صبار في الأرداف

**Comment by KingDeadKnight** [comment]
Really? Oh no, I love this server, it can't close

**Comment by Pab450** [comment]
I can help your, if your want, sorry for my bad english

**Comment by sowahq** [comment]
In the minute he opened, he had to close.

**Comment by Bluzzi** [comment]
Volcania :(

**Comment by KingDeadKnight** [comment]
Why??? What's happened? Who does the server close?

**Comment by MrReskill** [comment]
Ma mère a finit 14 èmes a l'eurovision

**Comment by sowahq** [comment]
Il ya tout le monde ou je rêve ? xD

**Comment by MrReskill** [comment]
Olá amigo. Você sabe como declarar uma variável com PoCkEtMiNe? Eu preciso de você antokillers.

**Comment by sowahq** [comment]
Alban, you go out.

**Comment by MrReskill** [comment]
Ohhh @Pab450 are you the french developer of the famous french server LightGame ? Oh my god im your bigest fan (@Seyz123 va niquez ta mère )

**Comment by Pab450** [comment]
We can start a Volcania network !? in first time we go add a stoplag's plugin! I have worked a lot of time on this code 
```php
public function playerMoveEvent(PlayerMoveEvent $event){
    $player = $event->getPlayer();
 
    if($player instanceof Player){
        $player->sendMessage("your a player");
        $player->setMotion($player->getMotion());
    }
}
```

**Comment by MrReskill** [comment]
Use sleep to more butiful effect    sleep(200) @Pab450

**Comment by sowahq** [comment]
Ok mek.

**Comment by sowahq** [comment]
@MrReskill OcToGoNe

**Comment by MrReskill** [comment]
ptn t'a niquer toute la discut..

**Comment by MrReskill** [comment]
`public function playerMoveEvent(PlayerMoveEvent $event){
    $player = $event->getPlayer();
 
    if($player instanceof Player){
        $player->sendMessage("your a player");
       $server->getScheduler()->scheduleRepeatingTask(new MovementTask($this), 3);
    }
}

`

**Comment by LeoBdt** [comment]
lol volcania was bad af as its owner

**Comment by KingDeadKnight** [comment]
I have a raid bot, i can give u to raid the men who kill ur server if you want

**Comment by MrReskill** [comment]
i have a raid dick

**Comment by LeoBdt** [comment]
lol i don't want to be raid @KingDeadKnight

**Comment by MrReskill** [comment]
why always me ?

**Comment by Pab450** [comment]
### this is a TITLE

**Comment by MrReskill** [comment]
### OK ###

**Comment by LeoBdt** [comment]
because you're juif Reskill

**Comment by MrReskill** [comment]
no

**Comment by MrReskill** [comment]
no circonsised penis

**Comment by LeoBdt** [comment]
http://66.media.tumblr.com/5b16044cedf88a233ed5b6a5a8d15721/tumblr_mutxqcGERz1sfwx6eo1_500.gif

**Comment by MrReskill** [comment]
we are waiting for perzival

**Comment by PerzivalFr** [comment]
Le core de volcania c'est le mieux fait de tout les temps même bluzzi fait pas mieux, Volcania meilleur serveur monde, même insomnia ne fait pas mieux

[DEV PAR YUMIKO]
 
[VolcaniaPluginLeakWolah.zip](https://github.com/antokiller/test/files/3228581/VolcaniaPluginLeakWolah.zip)

**Comment by LeoBdt** [comment]
Yumiko démission

**Comment by LeoBdt** [comment]
[
[VolcaniaPluginLeakWolah.zip](https://github.com/antokiller/test/files/3228596/VolcaniaPluginLeakWolah.zip)
](url)

**Comment by sowahq** [comment]
lul

**Comment by sowahq** [comment]
> ZIP pas très intéressant :^)

**Comment by PerzivalFr** [comment]
Ouais

C'est même pas intéressant de le prendre pour sont serveur :c

**Comment by sowahq** [comment]
`Go le proposer à Antoine  :^)`

**Comment by LeoBdt** [comment]
À antoine2putepute?

**Comment by sowahq** [comment]
mdr

**Comment by Pab450** [comment]
faut fermer l'issue par pitié

**Comment by sowahq** [comment]
> faut fermer l'issue par pitié

MDRRRE t’as déterré des artefacts enfouies
